### ISSUE TITLE
Admin Link Distribution Page

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#17]
If your an Admin, you should have access to a specific page that allows you to:

Take links from the LINKS table (which is associated with a publisher), and add them to the GeneratedLinks table (which is associated with a user). You must be able to assign them to a particular user. 

In the near future we will use the links helper to convert the links into their shortened form, where they can retrieve stats at any time. But for now we can just copy the full link.

**Comment by lef592** [comment]
Finished this specific issue.
