### ISSUE TITLE
Possibly switch to a different Theme which allows easier installs. 

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#18]
Looking into this now. Emailed the Admins and I'm waiting on a response. 

https://dresssed.com

**Comment by scojasp** [comment]
Take a look at branch unique_dashboards (try to login, dashboards) - in the meantime, I've put up a framework for a dashboard inspired by Flatty

**Comment by scojasp** [comment]
Fixed Flatty - now completely works. Check out my comment on Issue #2
