### ISSUE TITLE
Add radio button in signups for publisher/user

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#21]
:radio_button: User  |  :black_circle: Publisher

**Comment by Gondee** [comment]
How are publishers currently logging in? With User credentials? I don't see a flag/reference in the User schema to set/point

On the master btw

**Comment by scojasp** [comment]
Publishers currently log in through /login, as they are supposed to.

To me, makes no sense if publishers/users log in differently; if you do want to use your publishers table, we need to link the tables differently but Users needs to contain all people using the app. Probably can achieve this using a foreign key or something.

**Comment by scojasp** [comment]
And in order to make radio button, you'll need to manipulate the variable <code>publisher</code> which rn is a boolean

**Comment by Gondee** [comment]
I'm open to any logical way for them to login. Ok, so i accidentally checked out a local copy of master and didn't have the latest.

**Comment by scojasp** [comment]
Would very prefer if fixed to be in <code>flatty_integration</code> - want to get Flatty to <code>master</code> ASAP

**Comment by Gondee** [comment]
Done
