### ISSUE TITLE
Graphing Using Flatty plugins

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#22]
Once the Linkshortener gem can pull statistics, we can integrate it into the graph. In the mean time, figuring out how to implement/integrate the plugins would be a good task.

**Comment by scojasp** [comment]
If we cannot get this working very, very soon, we NEED to drop this for a fully functional site. Possibly add some graphical asthetical asset or some other function in its place.

**Comment by Gondee** [comment]
Working on a solution to this, lets discuss Wednesday

**Comment by Gondee** [comment]
Pretty close on this, have everything working except the data isn't assembled quite perfect.

**Comment by scojasp** [comment]
When you pass the data back, if it's doing weird things or being too literal, you may need to use:

<code>raw "[[1,300],[2,450],...]"</code>

**Comment by Gondee** [comment]
eb9edd7 Done
