### ISSUE TITLE
Customer Dashboard Theme/Layout

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#23]
See the our project checkpoint in Google Docs for reference of what it should kinda look like.

**Comment by scojasp** [comment]
Created branch <code>user_dashboard</code>: bf0dcd1
Intending to theme the data/dummy data in this fashion: 

![User Dashboard Prototype](https://dl.dropboxusercontent.com/u/12035250/CSCE436/user_dash_proto.jpg)

**Comment by lef592** [comment]
This is more or less done for now until we get the graph up.

**Comment by scojasp** [comment]
Merge into #22 due to the need of graphs
