### ISSUE TITLE
Add additional options when "Publisher" in signup is selected

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#33]
Publisher should lead to a "Company" box and a "Position" box. Thinking prob going to use Javascript.

**Comment by scojasp** [comment]
Harder than it initially appears. Hard to ask for variables the User object doesn't already have.

**Comment by Gondee** [comment]
I believe you can create a variable accessible from the view using @ in the controller method being used. 

Edit: Will require javascript

**Comment by scojasp** [comment]
Finished, and found out why I was messing up before
