### ISSUE TITLE
Why do we need the Publishers table separate from Users?

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#36]
We already have a boolean check if a user is a publisher, is there any special significance to having a Publishers table?

If a user is not a publisher, we can simply fill the blank cols in with NULLs.

Is there some special significance, what was your idea?

Also referencing #33 for good measure

**Comment by Gondee** [comment]
Long term I think it's important that there is a place to store lots of publisher only data, as well as an id that's for the publisher and not just the person who works for them. We will review today
