### ISSUE TITLE
Cache clicks for GeneratedLinks

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#49]
Store a cached amount of clicks in GeneratedLink.clicks and have it update occasionally, whenever accessed??

**Comment by Gondee** [comment]
Im going to work on this atm if there is not objections

**Comment by scojasp** [comment]
Go for it

**Comment by Gondee** [comment]
Heres how i worked it. When a user pulls a link, it updates the database with the current number. This way when publishers a querying potentially 10x the links on one page its less API use. Is done automatically, no need to change any code. Saves the total number to date btw.

**Comment by scojasp** [comment]
Sweeeeeet.
