### ISSUE TITLE
Switch to Post gres in local project

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#6]

**Comment by scojasp** [comment]
Created postgres_implementation branch and made some changes to the database adapters, but errors currently due to Cloud9 not auto-providing PG credentials

**Comment by Gondee** [comment]
I had similar issues messing with it today. This might do the trick

Postgresql setup section
https://github.com/Aerogami/guides/wiki/Cloud9-workspace-setup-with-Rails-and-Postgresql

**Comment by scojasp** [comment]
This is currently being worked on and is essential for Heroku - closing b/c inherent part of issue #1.
