### ISSUE TITLE
Missing Tags in Dashboard? 

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#67]
![image](https://cloud.githubusercontent.com/assets/5413555/11321079/d320f8fc-9076-11e5-893b-3ef7f89d8542.png)

Just noticed this

**Comment by scojasp** [comment]
On it

**Comment by scojasp** [comment]
Reverted all changed on page back to 2e10fdfbb1d65495843281e8096e8bbf47678ec2.
