### ISSUE TITLE
Chart scrunching up

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#69]
![untitled](https://cloud.githubusercontent.com/assets/5413555/11388510/a38cf374-92fc-11e5-9ec5-9cd37e5c65c4.png)

**Comment by Gondee** [comment]
@scojasp would you mind looking into this when you get a chance, your the resident expert on these things aha. Not critical tho

**Comment by scojasp** [comment]
Chart is scrunching up because it is fitting to the text; there is no arbitrary boundary being placed on it. However, will try to look into auto-adjusting tables adding whitespace based on screen width

**Comment by scojasp** [comment]
(Cont.) {Admin}/links does the same thing, will try to fix for all

**Comment by scojasp** [comment]
Had to use an extremely hacky approach to do it, because including 'data-table' in class outright generates new code that I cannot control, but all should be fixed.

Flatty's implementation of data tables is horrible.

Commit 5551657d26326c0a8b57bfe4bbced1d8c5750bfa
