### ISSUE TITLE
Change all instances of float dollar values to 2 decimal places

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#79]
Preferably rounded down.

For instance, some dollar values show $0.0 instead of $0.00, or $72.156 instead of $72.15

**Comment by Gondee** [comment]
My opinion is that we leave this at 3 decimal places, since per click is usually in the thousandths place.

**Comment by scojasp** [comment]
I realize that, however, I had thought I had seen at least one place where the dollar amount was blatantly off, in an incorrect spot.. Can't find it though, so closing
