### ISSUE TITLE
Switch from WebBrick to something Faster/Multi-threaded. 

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#8]
Webbrick is fine on the dev environment, but when deployed to production on Heroku, we need something a bit faster than can support multiple users.

**Comment by scojasp** [comment]
According to Heroku's website, <code>puma</code> is the preferred multithreaded choice.

https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server

However, being it _is_ multithreaded, when we test Puma, we will need to have mutually exclusive access to the Heroku.

**Comment by Gondee** [comment]
Sounds good to me, we can just deploy it on production only.

**Comment by Gondee** [comment]
Ok, added this to our first mile stone. So its plan of record now.

**Comment by lef592** [comment]
Tested puma some. Just installing the puma gem can be done, and puma WILL run, but I'm not sure it will work unless Heroku is properly set up. Since if I try this nothing of the website shows up. We might not be able to do this until later.

**Comment by lef592** [comment]
Ok. I believe I've done this. However, since it's for production there is still no testing it yet. This change will be included in static_pages branch when I finish.
