### ISSUE TITLE
Background job that updates a stats table with daily payment data - Expires generated links

### ISSUE THREAD

**Issue by Gondee** [Gondee/SocialCurveManager#81]
I literally couldn't find a way around this. So background tasks it is! 

Main Background task: Runs every night
1. gets daily total clicked amount for each and every generated link. Stores them so we can query by day. We get 1 million link shortener queries per day, so this should be fine. 
2. For links that expire that day, it updates their column named paidclicks which is the total clicks they will be paid for. These links will no longer be checked nightly too

http://ruby-journal.com/how-to-integrate-sidekiq-with-activejob/

**Comment by scojasp** [comment]
If you save your work to a branch, I could try to contribute to this later

**Comment by Gondee** [comment]
i have it up in a branch. Im having issues calling it to perform_later atm

**Comment by Gondee** [comment]
Calling it a night, will be back on it tomorrow.

**Comment by Gondee** [comment]
Note: https://docs.c9.io/docs/setting-up-redis
Note: http://bica.co/2015/03/08/using-active-job-with-sidekiq/
Starting SideKiq:bundle exec sidekiq -C ./config/sidekiq.yml
Checking that its running:  ps aux | grep sidekiq
Start Redis: redis-server

**Comment by Gondee** [comment]
Got it working. @scojasp do you have time to meet up tomorrow for a couple hours?

**Comment by scojasp** [comment]
@Gondee Sure, after class nothing going on til 4 or so

**Comment by Gondee** [comment]
sweet, meet you after class
