### ISSUE TITLE
Merge "Revert" to master

### ISSUE THREAD

**Issue by scojasp** [Gondee/SocialCurveManager#9]
If we are using Revert as the master branch and making changes to the current master is frowned upon, why don't we just make Revert the master branch? Doesn't make sense.

**Comment by Gondee** [comment]
Revert was just the branch for Laurn to do the login. It needs to be merged eventually, so this is fine with me.

**Comment by scojasp** [comment]
Gotcha, I was under the impression that Revert was going to be our master branch in the entire project.
Because this is obviously going to be merged like any other branch, closing.
